### ISSUE TITLE
Peekaboo with the navigation bar

### ISSUE THREAD

**Issue by bogdaaamn** [Virtual-Coffee/virtualcoffee.io#823] opened 2023-03-03 11:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Not sure if this is a bug or a feature, but the nav bar is visible but not interactive on scroll up all the way up on the landing page. Also it stay visible if there is focus within.

https://user-images.githubusercontent.com/22895284/222702927-615485f3-7192-467b-9b68-7b0fecd9dee2.mov

I think the idea is to hide the bar when scrolled all the way up and reveal it later, right? But I scrolled too much and revealed the bar by mistake, I can't unsee it and I wanna press it 😭 

### Steps To Reproduce

1. Go to https://virtualcoffee.io/
2. Scroll up for no reason

### What browsers are you seeing the problem on?

Chrome

### Environment

```markdown
- OS: MacOS Ventura 13.0
```

### Anything else?

I love issues forms, I didn't know we have them omg

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by danieltott** [comment] 2023-03-21 17:48
This is the expected behavior 👍🏼

**Comment by danieltott** [comment] 2023-03-21 17:51
Looks like `overscroll-behavior-y:none` might do it

**Comment by dreymoreau** [comment] 2023-03-22 16:16
hi! i would like to fix this bug :)

**Comment by danieltott** [comment] 2023-03-22 16:17
@dreymoreau it's all you!

**Comment by dreymoreau** [comment] 2023-03-22 18:49
![Preview README md - virtual-coffee - Visual Studio Code 2023-03-22 2_39_01 PM](https://user-images.githubusercontent.com/75917821/227006866-1
![Invocation Failed and 1 more page - Personal - Microsoft​ Edge 2023-03-22 2_39_09 PM](https://user-images.githubusercontent.com/75917821/227006880-83dacefc-05f8-4987-b1e7-18c178b7ad24.png)
48ee079-2e2f-4779-8b50-4c3645fe8582.png)

@danieltott 
hi! so this is what happened after following the instructions in the readme.md, wondering if i can get further clarification of what i need to do to build it?

**Comment by dreymoreau** [comment] 2023-03-22 18:51
![readme png](https://user-images.githubusercontent.com/75917821/227007303-6744fd16-80e4-4ddf-9351-b18343c564d4.png)
![error png](https://user-images.githubusercontent.com/75917821/227007342-2b882f1b-c829-43ca-9427-2cb82701c227.png)

@danieltott hi! followed the readme instructions but got this error when trying to build, wondering about further clarification on how to get it working when building locally?

**Comment by redapy** [comment] 2023-03-22 20:42
@danieltott sorry for the late response, I was a bit busy.  However, I can't reproduce the behavior on my MacOS Monterey 12.6. Please let me know if there is anything I can help with!

**Comment by danieltott** [comment] 2023-03-23 17:33
@dreymoreau just to cover our bases, I assume you tried to stop the server and re-start it?

Also, can you paste in the following versions:
- Node (`node -v`)
- yarn (`yarn -v`)
- netlify-cli (`netlify-cli -v`)

**Comment by dreymoreau** [comment] 2023-04-07 21:12
hi! sorry for getting back to you late
node version : 19.8.1
yarn version: 1.22.19
for netlify-cli, it prompts thism even though i have it installed and have used the command for the latest version

![Preview README md - virtual-coffee - Visual Studio Code 2023-04-07 5_11_03 PM](https://user-images.githubusercontent.com/75917821/230679695-a04017c1-cba3-4ec5-9a0d-dca291472dd2.png)

**Comment by sameer-soni** [comment] 2023-08-07 16:26
Hi there! I've created a pull request (#959 ) to address this issue. Please take a look when you have a moment. Thanks!

**Comment by danieltott** [comment] 2023-10-06 15:02
@dreymoreau I'm sorry about the delay helping you out here. Do you still want to take a crack at this? I believe @adiati98 has gotten the site running on windows so she may be able to help...

**Comment by adiati98** [comment] 2023-10-06 18:12
@danieltott as this is on the homepage where we need to fetch (fake?) data, it always crash on Windows.
I mostly work on newsletter and monthly challenge pages where we don't need to fetch data from 3rd party.

**Comment by dominicduffin1** [comment] 2023-10-10 18:29
If @dreymoreau still wants to work on this I might be able to help figure out how to get it running on Windows (I believe I did get it running in the past but I can't remember how🙂). Another option if your system supports it is to try Windows Subsystem for Linux (which I can also help with).

**Comment by adiati98** [comment] 2023-10-10 18:54
@dominicduffin1 I will be interested to know how to get the homepage running on Windows (not WSL... yet 😁).

**Comment by danieltott** [comment] 2024-09-30 16:26
closed via 74a0c079fb1d2a1b77acf8963af701706cfe6b50

**Closed by danieltott** 2024-09-30 16:26 UTC
Labels: Type: bug
