### ISSUE TITLE
Some style inconsistencies on the website

### ISSUE THREAD

**Issue by datsfilipe** [Virtual-Coffee/virtualcoffee.io#1037] opened 2023-10-06 14:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Well, I've noticed some problems with the styles on the website, like:

The header animation on scroll is not fully complete at some point (which is okay), but it starting from the bottom makes it looks strange. Seems that the header is also disappearing when focusing another window, but I'm not sure about that.

Other than that, some hover states should be added to footer and header links, and some buttons too. I think this would improve the UI of the website a lot!

### Steps To Reproduce

1. Scroll the page slowly to notice the header animation state in the image I will give below.
2. Hover links and buttons having no hover state.

### What browsers are you seeing the problem on?

Chrome

### Environment

```markdown
- OS: Arch
- Node: not relevant
- pnpm: not relevant
```

### Anything else?

Here a image showing the header animation on scroll when it looks strange:

![image](https://github.com/Virtual-Coffee/virtualcoffee.io/assets/76636791/71d1f3fb-bd77-4ed4-ab19-e82fbde00a09)

I will not take screenshots of the other things but if you visist the website you will notice the links behavior and so on.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Virtual Coffee community

**Comment by danieltott** [comment] 2023-10-06 15:04
Hey @datsfilipe - thanks for the issue!

We already have an issue about the navbar, although most of what you describe is by design: #823

The header links _do_ have a hover state, and since the footer links are so simple, I don't really think they need a hover state.

I'm going to go ahead and close this issue, but thank you again for taking a look!

**Closed by danieltott** 2023-10-06 15:04 UTC
Labels: Type: bug, Status: Needs Triage

**Comment by datsfilipe** [comment] 2023-10-06 15:12
Oh, didn't saw the that issue about the navbar, my bad. But still, the links state is not intuitive for the end user at all. Not having hover states is pretty awful, but not just that, look:

https://github.com/Virtual-Coffee/virtualcoffee.io/assets/76636791/ae36d416-2734-441e-ad79-f37ca6c03abd

The user clicking on the background and being redirected to another website is the oppositte of intuitive. It's not even a UI issue, but a UX one. But it's okay if you don't think those changes are necessary! :)
